version: 2.1
jobs:
  prepare:
    docker:
      - image: cimg/node:12.18.0
    steps:
      - checkout
      - run: 'yarn'
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - node_modules

  build:
    docker:
      - image: cimg/node:12.18.0
    steps:
      - checkout
      - run: 'yarn build'

  test:
    docker:
      - image: cimg/node:12.18.0
    steps:
      - checkout
      - run: 'yarn test'

workflows:
  build_and_test:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
