/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ChallengeManagerInterface extends ethers.utils.Interface {
  functions: {
    "currentStatus()": FunctionFragment;
    "fraudDetected(uint256,string)": FunctionFragment;
    "split(tuple,bytes32[],tuple,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "currentStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fraudDetected",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "split",
    values: [
      { witness: BytesLike; index: BigNumberish; nodes: BytesLike[] },
      BytesLike[],
      { witness: BytesLike; index: BigNumberish; nodes: BytesLike[] },
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fraudDetected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "split", data: BytesLike): Result;

  events: {};
}

export class ChallengeManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ChallengeManagerInterface;

  functions: {
    currentStatus(overrides?: CallOverrides): Promise<[number]>;

    fraudDetected(
      index: BigNumberish,
      _mover: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    split(
      _consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _hashes: BytesLike[],
      _disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _mover: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  currentStatus(overrides?: CallOverrides): Promise<number>;

  fraudDetected(
    index: BigNumberish,
    _mover: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  split(
    _consensusProof: {
      witness: BytesLike;
      index: BigNumberish;
      nodes: BytesLike[];
    },
    _hashes: BytesLike[],
    _disputedProof: {
      witness: BytesLike;
      index: BigNumberish;
      nodes: BytesLike[];
    },
    _mover: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    currentStatus(overrides?: CallOverrides): Promise<number>;

    fraudDetected(
      index: BigNumberish,
      _mover: string,
      overrides?: CallOverrides
    ): Promise<void>;

    split(
      _consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _hashes: BytesLike[],
      _disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _mover: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    currentStatus(overrides?: CallOverrides): Promise<BigNumber>;

    fraudDetected(
      index: BigNumberish,
      _mover: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    split(
      _consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _hashes: BytesLike[],
      _disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _mover: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    currentStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fraudDetected(
      index: BigNumberish,
      _mover: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    split(
      _consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _hashes: BytesLike[],
      _disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _mover: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
