/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DisputeGameManagerInterface extends ethers.utils.Interface {
  functions: {
    "checkWitnesses(tuple,tuple)": FunctionFragment;
    "interval()": FunctionFragment;
    "split(tuple,bytes32[],tuple,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkWitnesses",
    values: [
      { witness: BytesLike; index: BigNumberish; nodes: BytesLike[] },
      { witness: BytesLike; index: BigNumberish; nodes: BytesLike[] }
    ]
  ): string;
  encodeFunctionData(functionFragment: "interval", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "split",
    values: [
      { witness: BytesLike; index: BigNumberish; nodes: BytesLike[] },
      BytesLike[],
      { witness: BytesLike; index: BigNumberish; nodes: BytesLike[] },
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkWitnesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "interval", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "split", data: BytesLike): Result;

  events: {};
}

export class DisputeGameManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DisputeGameManagerInterface;

  functions: {
    checkWitnesses(
      consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<[void]>;

    interval(overrides?: CallOverrides): Promise<[BigNumber]>;

    split(
      consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      hashes: BytesLike[],
      disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  checkWitnesses(
    consensusProof: {
      witness: BytesLike;
      index: BigNumberish;
      nodes: BytesLike[];
    },
    disputedProof: {
      witness: BytesLike;
      index: BigNumberish;
      nodes: BytesLike[];
    },
    overrides?: CallOverrides
  ): Promise<void>;

  interval(overrides?: CallOverrides): Promise<BigNumber>;

  split(
    consensusProof: {
      witness: BytesLike;
      index: BigNumberish;
      nodes: BytesLike[];
    },
    hashes: BytesLike[],
    disputedProof: {
      witness: BytesLike;
      index: BigNumberish;
      nodes: BytesLike[];
    },
    _caller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    checkWitnesses(
      consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<void>;

    interval(overrides?: CallOverrides): Promise<BigNumber>;

    split(
      consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      hashes: BytesLike[],
      disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _caller: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkWitnesses(
      consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interval(overrides?: CallOverrides): Promise<BigNumber>;

    split(
      consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      hashes: BytesLike[],
      disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkWitnesses(
      consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interval(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    split(
      consensusProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      hashes: BytesLike[],
      disputedProof: {
        witness: BytesLike;
        index: BigNumberish;
        nodes: BytesLike[];
      },
      _caller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
